# Site settings
title: Masih's Personal Blog # site title
description: >- # site description
    I am a computer science student born in Iran (currently based in Germany) and am mainly interested in embedded systems, compiler design (still didn't finish reading the dragon book &#128517;) and computer architecture.</br>
    Follow me on Github: <a href="https://github.com/Masihtabaei" target="_blank" rel="noopener">@github</a>.
lang: en-US # default lang
timezone: Europe/Berlin # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/piharpi/jekyll-klise # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Masih # author name
  bio: >- # tell to the world
    I am a computer science student born in Iran (currently based in Germany) and am mainly interested in embedded systems, compiler design (still didn't finish reading the dragon book &#128517;) and computer architecture.</br>
    Follow me on Github: <a href="https://github.com/Masihtabaei" target="_blank" rel="noopener">@github</a>.
  username: Masihtabaei # general username
  github: Masihtabaei # github username
  twitter:  Masihtabaei # twitter username
  facebook: facebook_username # facebook username
  email: your-email@email.com # email adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://masihtabaei.github.io/" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
